### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by richardlthomas** [tualo/tualo-git-context#11]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:57:13)
<unknown> (/Users/rthomas/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:201:13)
ChildProcess.exithandler (child_process.js:720:7)
emitTwo (events.js:87:13)
```

**Comment by thomashoffmann1979** [comment]
Thanks a lot for filing this issue, i have fixed it in version 0.5.0.
