### ISSUE TITLE
Crashing and errors

### ISSUE THREAD

**Issue by ProLoser** [tualo/tualo-git-context#14]
This plugin is completely crashing atom and throwing a bunch of errors. It's causing it to completely lock up.

**Comment by thomashoffmann1979** [comment]
please post those error messages

**Comment by thomashoffmann1979** [comment]
Thanks, i can reproduce it with large projects. I will fix it soon.

**Comment by thomashoffmann1979** [comment]
I have fixed that issue. Maybe your issue #13 is fixed also with that.
