### ISSUE TITLE
Unreadable text in tree-view with Atom Light theme

### ISSUE THREAD

**Issue by mark-hahn** [tualo/tualo-git-context#2]
See image below. When I open a folder in the tree-view the file names appear with normal color but then in a second or two they change to an unreadable text color, at least to my eyes on my monitor.

![gray](https://cloud.githubusercontent.com/assets/811455/3546420/7542de20-0883-11e4-850c-5665d97842a3.jpg)

I'll look for the CSS for this.

**Comment by thomashoffmann1979** [comment]
Thanks a lot for filing this issue, i have fixed it in version 0.5.0.
