### ISSUE TITLE
Error being thrown when no Tree View present

### ISSUE THREAD

**Issue by deankarn** [tualo/tualo-git-context#5]
When I start Atom, and have yet to open a project or folder the tree view is not present this plugin is throwing an error:

Uncaught TypeError: Cannot read property 'getEntries' of null /Users/username/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:236

and another

Uncaught TypeError: Cannot read property 'getEntries' of null tualo-git-context-view.coffee:191module.exports.TualoGitContextView.refreshTree tualo-git-context-view.coffee:191

![screen shot 2014-10-07 at 10 15 54 pm](https://cloud.githubusercontent.com/assets/8068371/4553010/4de80680-4e91-11e4-9dcc-ba5fa7bfac81.png)

**Comment by thomashoffmann1979** [comment]
Thanks a lot for filing this issue, i have fixed it in version 0.5.0.
