### ISSUE TITLE
"Only modified files can be added to the stage! tualo-git-context-view.coffee:105"

### ISSUE THREAD

**Issue by sbromberger** [tualo/tualo-git-context#6]
I can't seem to stage any files. They've been modified and saved, but I keep getting this error.
- I make a change to a tracked file
- I save it
- I use the "GIT Stage" context menu on the file sidebar
- I receive this console message.

"GIT Status" shows the file as "modified".

**Comment by sbromberger** [comment]
Update:

This package appears to be significantly broken with the latest Atom. The section of code that sets the classes indicating git-status is not selecting the correct items (requires full pathing, and it's using relative), so nothing's working right.

**Comment by thomashoffmann1979** [comment]
Thanks a lot for filing this issue, i have fixed it in version 0.5.0.
